name: Draw Charybdis ZMK keymaps
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - "config/charybdis.keymap"
      - "config/custom/*.keymap"
      - "config/custom/*.dtsi"
      - "config/custom/key-labels/*.h"
      - "boards/shields/charybdis/charybdis_layout.dtsi"
      - "img/charybdis/config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      commit_message: "docs(bot/draw): [${{ github.event.head_commit.message }}]"
      keymap_patterns: "config/charybdis.keymap" # path to the keymaps to parse
      config_path: "img/charybdis/config.yaml" # config file, ignored if not exists
      output_folder: "img/charybdis" # path to save produced SVG and keymap YAML files
      parse_args: "" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "charybdis:'-k bastardkb/charybdis/3x5'"  # change 3x5 to 3x6 or 4x6 as appropriate
